language: python
python:
- '2.7'
install:
- pip install tox
script: tox
notifications:
  slack:
    secure: 2v8kgduBc3rb2+0ChQ8bDLtaZele0MptePBo39DISoNMfip05T0ZkEp56lpvs+IGiT/lRNCwP8bgUYLMNxVNQd1EtGLsqnDtWTb6zKWdfv41CRePMUL1Uj7bCTtSfRKZzWAJqyVAbjW5dPmXHIUnmq7p945g6Kk/tuRLIGjMN+8o2qRmmt10QYvbQK+b6pI72Qpx46MDrhOfRqJCiPrrLQ+Ankv3TWrtH4DDgdBlvjMHc3QbkNRbYXWgoLi/fE4/E1RAHds6VfxQ2jabBdoro0MHFSBGT987BnIKGoaKriA9Wcycck1AWOoxnaZp6/kzzeW5Ipju+7+AdKux4n2DiNOgcCq8RQmEMpvKTdb5E/FK+P9rgYqZv8TQFJpeMC315i/JoqUwANBDOKX7vsiG+WyHUyon2J0Oz7vLa+5XoNajwdALfKkZ5IPerXgYGXQ7FMlE1ZPxfYf/XO9ZgJn2qwra8P062fhGnKZRnKAbMrFFG0jJwykv6DgWVROzvMUi7jwiXb5Bz1Z2pmF7xCMbnaXU8aT3znTKxIDJQ7FQTpNpu2I4thh+Bsyz50yexIdTe7pl5RvtGhTDo9XJjhd9wKJv2eT8/qZK1vrWYap585TWu7kgRynwrOREkpm5lVWsWEimrXTBVOfawV5l2Pu18wA/NyV1863DC/AeitT7h9w=
